site_name: Collaborative Up Voting Lists

# Repository
repo_name: 'CollaborativeList'
repo_url: 'https://github.com/TeamGhostBuster/CollaborativeList'

theme: material
pages:
    - Collaborative Lists: index.md
    - Software Requirenments:
        - Project Overview: requirement-document/project-overview.md
        - Project Glossary: requirement-document/project-glossary.md
        - Storyboard: requirement-document/storyboard.md
        - User Story: requirement-document/user-stories.md
        - Technical Resources: requirement-document/technical-resources.md
        - Similar Products: requirement-document/similar-products.md
    - Software Design:
        - System Overview: software-design/software-design.md
        - Detail Design: software-design/detail-design.md
    - Contribution Code: contribution-code.md
    - Credit: credits.md

markdown_extensions:
    - admonition
    - toc(permalink=true)
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde

extra:
    palette:
        primary: Teal
        accent: Cyan
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
